version: "3.8"

services:

  configurator:
    image: narayanpratap86/configurator:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - narayanbank

  eurekaserver:
    image: narayanpratap86/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - narayanbank
    depends_on:
      - configurator
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configurator:8071/

  accounts:
    image: narayanpratap86/accounts:v1.0.02
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - narayanbank
    depends_on:
      - configurator
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configurator:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
  loans:
    image: narayanpratap86/loans:v1.0.02
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - narayanbank
    depends_on:
      - configurator
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configurator:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    
  cards:
    image: narayanpratap86/cards:v1.0.02
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - narayanbank
    depends_on:
      - configurator
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configurator:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
   
  gatewayserver:
    image: narayanpratap86/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - narayanbank
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      
networks:
  narayanbank: